In [1]:
import sympy as sym
from IPython.display import display, Math 

In [2]:
x = sym.symbols('x')

In [10]:
t = x**2-1/x-1

In [11]:
t

x**2 - 1 - 1/x

In [12]:
display(t)

x**2 - 1 - 1/x

In [26]:
import numpy as np
from numpy import linalg

In [17]:
a = np.arange(1,10)

In [18]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a = [0,0,2,1,2]
b = [0,1,0,2,-1]
c = [1,2,0,-2,1]
d = [0,0,0,-1,1]
e = [0,1,-1,1,-1]
a,b,c,d,e

([0, 0, 2, 1, 2],
 [0, 1, 0, 2, -1],
 [1, 2, 0, -2, 1],
 [0, 0, 0, -1, 1],
 [0, 1, -1, 1, -1])

In [22]:
n = np.array([a,b,c,d,e])

In [23]:
n

array([[ 0,  0,  2,  1,  2],
       [ 0,  1,  0,  2, -1],
       [ 1,  2,  0, -2,  1],
       [ 0,  0,  0, -1,  1],
       [ 0,  1, -1,  1, -1]])

In [24]:
c = np.array([1,1,-4,-2,-1])
c

array([ 1,  1, -4, -2, -1])

In [27]:
jawab = linalg.solve(n,c)

In [28]:
jawab

array([ 3., -2.,  1.,  1., -1.])