In [1]:
import numpy as np

In [3]:
coba = np.arange(1,11)
coba

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
coba+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
coba+coba

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
coba*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
coba/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [8]:
coba%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [9]:
coba/coba

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
coba1 = np.arange(0,11)
coba1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
1/coba1

C:\Users\elsyanu\AppData\Local\Temp\ipykernel_15196\4131337418.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/coba1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [12]:
np.sqrt(coba1) # perintah sqrt di numpy untuk akar

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [14]:
np.exp(coba1) # perintah exp itu exponantial

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [15]:
np.cos(coba1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [16]:
np.sin(coba1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [17]:
np.sum(coba1)

55

In [18]:
np.log(coba1)

C:\Users\elsyanu\AppData\Local\Temp\ipykernel_15196\395689383.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(coba1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])