In [1]:
import numpy as np

In [2]:
angka = [1,2,3]

In [3]:
angkanp = np.array(angka)

In [4]:
angkanp

array([1, 2, 3])

In [5]:
angka*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
angkanp*3

array([3, 6, 9])

In [7]:
versilist = [[1,2,3],[4,5,6],[7,8,9]]
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
versinumpy = np.array(versilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.linspace(0,8,12)

array([0.        , 0.72727273, 1.45454545, 2.18181818, 2.90909091,
       3.63636364, 4.36363636, 5.09090909, 5.81818182, 6.54545455,
       7.27272727, 8.        ])

In [16]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [17]:
print(a[0])

[1 2 3 4]


In [18]:
print(a[1])

[5 6 7 8]


In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])