In [1]:
import numpy as np

In [2]:
# bilangan distibusi uniform (0-1)
np.random.rand(4)

array([0.99609408, 0.63953817, 0.19488148, 0.58411337])

In [3]:
# bilangan distibusi uniform (0-1) matriks dua dimensi
np.random.rand(3,4)

array([[0.85986162, 0.50280185, 0.79102861, 0.40283046],
       [0.89703154, 0.39043407, 0.38894802, 0.85627795],
       [0.15017441, 0.25472638, 0.25126136, 0.21088303]])

In [4]:
# bilangan ditribusi normal (gaussian)
np.random.randn(10)

array([ 0.87236854, -0.86511348,  0.21047147,  0.55191162,  0.09098057,
        0.86746592,  1.14195012,  0.55484271, -2.08032754, -0.07171297])

In [5]:
# bilangan ditribusi normal (gaussian) matriks dua dimensi
np.random.randn(4,4)

array([[-0.57405724,  1.2522066 , -1.2324503 ,  0.3347887 ],
       [-0.58197334, -0.06870711,  0.68664081,  0.82709135],
       [-0.45724745, -0.14219416, -0.83285916, -1.99240285],
       [ 0.62645236,  0.76965751,  0.84723203,  1.55346643]])

In [10]:
from numpy.random import randn, randint

In [11]:
randn(3,5)

array([[-1.05851901, -0.78335775, -0.58306674,  1.14491084, -0.38650574],
       [-0.41423671,  0.28046706,  0.61253848,  0.04522002,  0.47253481],
       [ 0.2811853 , -1.84072737, -0.45021689, -0.58676342,  0.66116967]])

In [14]:
randint(0,10)

3

In [15]:
randint(0,10,5)

array([0, 9, 2, 7, 0])

In [16]:
bilangan = randint(0,100,20) # untuk menjadikan randint 2 dimensi menggunakan reshape

In [17]:
bilangan

array([52, 24, 12, 11, 68, 56, 56,  4, 83, 61, 77, 95, 66, 24, 16, 20, 35,
       85, 43, 58])

In [18]:
bilangan.reshape(4,5) # yang berada di dalam kurug jumlahnya harus sesuai dengan bilangan 20 di atas

array([[52, 24, 12, 11, 68],
       [56, 56,  4, 83, 61],
       [77, 95, 66, 24, 16],
       [20, 35, 85, 43, 58]])

In [22]:
bilangan.shape

(20,)

In [28]:
bilangan2 = randint(1,20,20).reshape(5,4)

In [29]:
bilangan2

array([[19,  4,  8,  6],
       [ 4,  7, 15, 11],
       [16, 18,  1, 14],
       [15,  7,  8, 14],
       [ 9,  7,  4, 10]])

In [25]:
bilangan2.shape

(15,)

In [31]:
bilangan2.reshape(2,10)

array([[19,  4,  8,  6,  4,  7, 15, 11, 16, 18],
       [ 1, 14, 15,  7,  8, 14,  9,  7,  4, 10]])

In [33]:
bilangan2

array([[19,  4,  8,  6],
       [ 4,  7, 15, 11],
       [16, 18,  1, 14],
       [15,  7,  8, 14],
       [ 9,  7,  4, 10]])

In [34]:
# ganti dengan variabel baruatau samakan dengan variable di atas
bilangan2 = bilangan2.reshape(2,10)

In [35]:
bilangan2

array([[19,  4,  8,  6,  4,  7, 15, 11, 16, 18],
       [ 1, 14, 15,  7,  8, 14,  9,  7,  4, 10]])