In [1]:
from numpy.random import rand, randn, randint 

In [2]:
coba1 = randint(0,100,20)
coba2 = randint(0,100,20).reshape(4,5)

coba2

array([[35, 64, 44, 88, 69],
       [77, 34, 75,  9, 87],
       [ 9, 64,  6, 34, 35],
       [86, 83, 13,  9, 63]])

In [3]:
coba1

array([23, 67, 57, 76, 38, 79, 52, 87, 48, 56, 39, 17, 57, 45, 82, 22, 19,
       41, 36, 57])

In [4]:
coba1.max()

87

In [5]:
coba2.max()

88

In [6]:
coba1.min()

17

In [7]:
coba2.min()

6

In [8]:
coba2.argmax()

3

In [9]:
coba2

array([[35, 64, 44, 88, 69],
       [77, 34, 75,  9, 87],
       [ 9, 64,  6, 34, 35],
       [86, 83, 13,  9, 63]])

In [10]:
coba2.argmax()

3

In [11]:
coba2.argmin()

12

In [12]:
coba2.dtype

dtype('int32')

# indexing numpy

In [13]:
import numpy as np

In [14]:
coba = np.arange(0,11)
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
coba[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
coba[:5:9]

array([0])

In [19]:
coba[5:9]

array([5, 6, 7, 8])

In [20]:
coba2 = coba.copy()

In [21]:
coba2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
coba2[:5] = 100

In [23]:
coba2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [24]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
bilangan = np.array([[1,2,3],[4,5,6],[7,8,9]])
bilangan

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
bilangan[0][0]

1

In [27]:
bilangan[1][1]

5

In [28]:
bilangan[1,1] # indexing di numpy 

5

In [ ]:
bilangan[2:,1:]

# slicing dengan boolean di numpy

In [29]:
bil = np.arange(1,10)

In [30]:
bil

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
angka = bil>6

In [32]:
angka

array([False, False, False, False, False, False,  True,  True,  True])

In [33]:
bil = bil[angka]

In [34]:
bil

array([7, 8, 9])

In [35]:
bil

array([7, 8, 9])

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [4]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
b = np.array([2, 0, 1, 1])

In [13]:
b

array([2, 0, 1, 1])

In [14]:
a[np.arange(4), b]

array([ 3,  4,  8, 11])

In [16]:
a[np.arange(4), b] += 10
a

array([[ 1,  2, 23],
       [24,  5,  6],
       [ 7, 28,  9],
       [10, 31, 12]])

In [17]:
x = np.array([[1,2],[3,4]])

In [18]:
x

array([[1, 2],
       [3, 4]])

In [19]:
np.sum(x)

10

In [20]:
np.sum(x, axis=0)

array([4, 6])

In [21]:
np.sum(x, axis=1)

array([3, 7])

In [22]:
c = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
d = np.array([1,0,1])
d

array([1, 0, 1])

In [24]:
e = np.empty_like(c)
e

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
for i in range(4):
    e[i, :] = c[i, :] + d
    print(e)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [30]:
f = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12],[20, 30, 40],[50, 70, 100]])
f

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [ 20,  30,  40],
       [ 50,  70, 100]])

In [31]:
g = np.array([2,0,1,0])
g

array([2, 0, 1, 0])

In [35]:
h = np.empty_like(f)
h

array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       [      0,     508,       0],
       [      0, 6357108,       0],
       [5505116, 7143525,     112]])

In [36]:
for x in range(3):
    h[x, :] = f[x, :] + g
    print(h)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 